### ISSUE TITLE
monorepo 方式组织代码

### ISSUE THREAD

**Issue by xiaoxiangmoe** [umijs/umi-plugin-library#1]
* https://github.com/umijs/umi-plugin-library/blob/40fa86f2220b2338704a1e52d8ab7417bc218d8f/packages/docz-theme-antd/package.json
* https://github.com/umijs/umi-plugin-library/blob/40fa86f2220b2338704a1e52d8ab7417bc218d8f/package.json

我们在这里可以看到是嵌套形式的 package.json 这样子会导致根部的依赖，直接被 packages/docz-theme-antd/ 目录下的项目继承使用的。

为什么不把两个项目都放进 packages 目录下，用 yarn workspace 或者 lerna 管理呢？

**Comment by clock157** [comment]
`docz-theme-antd` 是验证方案时临时加的，后面我考虑拿出来，或者采用你说的 lerna，我试下。谢谢建议 @xiaoxiangmoe

**Comment by xiaoxiangmoe** [comment]
@clock157 我也是把项目和项目的 example 放在同一个 repo 管理的，比如我现在撸的那个 ts 的宏

https://github.com/xiaoxiangmoe/typescript-macros/blob/56ccf1007e8849e0fd37e72fcf285384f9dd2b56/package.json#L25-L29

这里通过 yarn 的 workspace 功能，指定了 packages 目录和 examples 目录，我把不会发布的东西，都丢到了 examples 目录，就是为了我自己 验证方案 使用的

**Comment by clock157** [comment]
重构了一波，接受继续监督和提醒~ @xiaoxiangmoe
