### ISSUE TITLE
主题更换

### ISSUE THREAD

**Issue by afc163** [umijs/umi-plugin-library#10]
不要用 ant design pro 的主题，默认用 docz 的吧。

**Comment by clock157** [comment]
好，主题是个大坑儿，半成品暴露不太好，我先把其他搞好。😅

**Comment by sorrycc** [comment]
ant design pro 可以作为额外的主题插件开启，不内置。

**Comment by ruizhengyun** [comment]
比如 umi 本地启动 8000 端口，但是 http://localhost:8000/color.less 是404，单 ant design pro 源码在本地启动的服务 http://localhost:8001/color.less 是可以查看的，求解
