### ISSUE TITLE
TypeScript 支持

### ISSUE THREAD

**Issue by xiaoxiangmoe** [umijs/umi-plugin-library#2]
ant-design 是一个 TypeScript 项目，希望 docz-theme-antd 会提供 TypeScript 的示例

**Comment by clock157** [comment]
好，我也正在学习 typescript ，立个 flag。

- [ ]  docz-theme-antd  typescript支持。

**Comment by tolerance-go** [comment]
> 希望 docz-theme-antd 会提供 TypeScript 的示例

**Comment by jiechud** [comment]
项目现在能对 ts 编译吗？

**Comment by clock157** [comment]
预计这个周末支持
