### ISSUE TITLE
input 参数要不要改成 entry? 

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi-plugin-library#24]
和项目的保持一致。

**Comment by clock157** [comment]
因为 [rollup](https://github.com/rollup/rollup/releases/tag/v1.0.0) 用的 input。你说的项目是指 umi 的入口吗？

**Comment by sorrycc** [comment]
是的，对于用户来说不需要知道后面是 rollup。另外，后面还要支持多 entry 的场景，比如 dva 的场景：

```js
entry: {
  dva: './src/index.js',
  fetch: './fetch.js',
  ...
}
```

**Comment by clock157** [comment]
OK, 那改下。
