### ISSUE TITLE
怎么配置  css loader 属性

### ISSUE THREAD

**Issue by jiechud** [umijs/umi-plugin-library#53]
怎么配置 css loader 属性
 如我想要配置cssLoader 的  `camelCase: true`

**Comment by clock157** [comment]
这个我加一下

**Comment by clock157** [comment]
这个需求强烈吗，有什么效果？因为我们开发用的是 webpack，实际打包库是用 rollup 做，一套规则需要实现两次，所以尽量简化配置达到通用。

**Comment by jiechud** [comment]
这个属性在 less 文件中可以这些写
```
ui-box {
  color: red
}
```
在 React 中， 通过cssModules 的方式可以这样用
```
import styles form './index.less'

<div className={styles.uiBox}></div>
```

**Comment by clock157** [comment]
理解了，可以支持，只是 css modules 你可以不用考虑重名啥的，直接使用 box 之类更简单

**Comment by clock157** [comment]
@jiechud  你可以通过这种方式实现
```js
export default {
  plugins: [
    [
      'umi-plugin-library', {
        cssModules: {
            camelCase: true
         }
      }
    ]
  ],
}
```

**Comment by jiechud** [comment]
@clock157 

配置如下，不生效
![image](https://user-images.githubusercontent.com/9709396/51830680-5fd6f680-232b-11e9-90f6-2f2bf7b91094.png)

**Comment by clock157** [comment]
是 build 还是 doc 中

**Comment by jiechud** [comment]
doc 中， builid 还没测试

**Comment by clock157** [comment]
确认有点小问题，fixed，这波 pr 可能要明天才能被合和发布。

**Comment by jiechud** [comment]
OK, 明天会和支持 ts 一起发布吗
