### ISSUE TITLE
sass支持需要如何配置

### ISSUE THREAD

**Issue by Gaven-Xu** [umijs/umi-plugin-library#63]
按umi的配置说明，在.umirc.js中配置了sass，也本地安装了node-sass和sass-loader，并没有生效，依然提示我需要loader来处理scss文件类型

**Comment by clock157** [comment]
建议使用 `less`，技术栈统一便于问题排查和处理。说下你的需求呢，我稍后可以支持。

**Comment by Gaven-Xu** [comment]
> 建议使用 `less`，技术栈统一便于问题排查和处理。说下你的需求呢，我稍后可以支持。

嗯，使用less也问题不大，我只是看umi支持sass，然后以为配置是同样的。
那么，我说下我现在遇到的问题，我再写UI库，那么我需要配置全局的一些less变量，该怎么写比较合理呢，我尝试了umi文档里的global.less方法，但是并不能生效

**Comment by sorrycc** [comment]
先不支持，文档里可以写明支持的项和不支持的项。
