### ISSUE TITLE
umi-plugin-react theme 样式没有应用上

### ISSUE THREAD

**Issue by tolerance-go** [umijs/umi-plugin-library#72]
https://umijs.org/zh/config/#theme

项目里设置了 theme 为非圆角，预览文档时候，看到的依然是 antd 默认样式

https://github.com/umijs/umi-plugin-library/issues/67

**Comment by clock157** [comment]
目前没有支持，可以看一下。你可以在创建一个 global.less在index引入，在这里定义变量。
