### ISSUE TITLE
[RFC] 写个插件支持解析 ts，js代码

### ISSUE THREAD

**Issue by DiamondYuan** [umijs/umi-plugin-library#94]
https://github.com/react-component/switch/issues/38

**Comment by DiamondYuan** [comment]
我可以帮忙

**Comment by xiaoxiangmoe** [comment]
@DiamondYuan 这个已经抛弃了，去使用 https://github.com/umijs/umi/tree/master/packages/umi-library 吧。

------

话说什么是“支持解析 ts，js代码”？

**Comment by DiamondYuan** [comment]
> @DiamondYuan 这个已经抛弃了，去使用 https://github.com/umijs/umi/tree/master/packages/umi-library 吧。
> 
> 话说什么是“支持解析 ts，js代码”？

https://github.com/DiamondYuan/interface-comments-parser

类似于这个。

**Comment by DiamondYuan** [comment]
转移阵地 https://github.com/umijs/umi/issues/2140

**Comment by clock157** [comment]
@DiamondYuan 你好，感谢你的意见，如 @xiaoxiangmoe 所说，已转移哈。
