### ISSUE TITLE
umi-library1.5生成doc报错，theme路径不对，windows系统，具体看截图

### ISSUE THREAD

**Issue by mankeheaven** [umijs/umi-plugin-library#95]
![image](https://user-images.githubusercontent.com/17426397/56779551-1a34a780-680e-11e9-91f1-39ba7b773bd4.png)

**Comment by sorrycc** [comment]
是个 bug，有兴趣提 PR 改下？

**Comment by mankeheaven** [comment]
sorry，最近好忙啊

**Comment by Iixianjie** [comment]
遇到同样的问题，降低版本也无效o(╥﹏╥)o

**Comment by mankeheaven** [comment]
@lixianjie 可以先手动改改docz这个theme的路劲用着。应该是生成theme的path的时候这块代码有bug.window下\\,比如 import Theme from 'D:\\maptalker\\maptalks-ui\\node_modules\\docz-theme-umi\\es\\index'
但是这个依赖于antd的ui组件会导致其他测试问题（开发无问题，这个ui测试也没问题）。ui本身的jest测试通过。但是对于用这个ui的项目而言，jest在import 某个组件的时候，css这块的引入，jest解析不了。报类似于下面的错误
  /Users/xxx/sources/proj/node_modules/antd/es/card/style/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import '../../style/index.less';

**Comment by sorrycc** [comment]
希望我今天能有时间修下这个，🙄

**Comment by woshiguabi** [comment]
![image](https://user-images.githubusercontent.com/17465858/57188138-33cfa080-6f2c-11e9-814f-c6e2b5596697.png)
在theme设置中手动传入一次可以解决
